### ISSUE TITLE
Is possible to directly stabilize the camera feed, not the recorded video?

### ISSUE THREAD

**Issue by websoft-ie** [yossato/virtualgimbal_ros#4]
I already ran your virtualgimbal repo for the recorded video.
But that is using the estimated optical flow calculated from the recorded video.
That says it is impossible to use for the camera feed, not the recorded video?
I would be very appreciate if you would help me with this issue.
Thank you and best regards.

**Comment by yossato** [comment]
This virtualgimbal_ros stabilizes the camera feed as I mentioned in https://github.com/yossato/virtualGimbal/issues/29#issuecomment-977870360 .

It generates stabilized video stream from original video stream and angular velocity from gyro sensor. It works in realtime for a full HD (1920x1080) video stream using Intel HD Graphics. It depends on ROS (Robot Operating System) middle ware since ROS helps a rapid prototyping.
